---
# epel release can't be merged with ansible,
# as it needs an additional update
- name: install epel-release
  yum:
    name: epel-release
    state: latest
    update_cache: yes

- name: install dependencies
  yum:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - git
    - ansible

- name: create ansible master group
  group:
    name: "{{ master.group }}"
    gid: 1400
    state: present

- name: create ansible master user with ssh key
  user:
    name: "{{ master.owner }}"
    group: "{{ master.group }}"
    uid: 1400
    generate_ssh_key: "{{ master.generate_ssh_key }}"
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa

- name: create the ansible master directory
  file:
    name: "{{ master.base_path }}"
    state: directory
    owner: "{{ master.owner }}"
    group: "{{ master.group }}"

- name: copy the ansible master pubkey
  copy:
    src: "/home/{{ master.owner }}/.ssh/id_rsa.pub"
    dest: "{{ master.base_path }}/ansible_master_rsa.pub"
    remote_src: yes
    owner: "{{ master.owner }}"
    group: "{{ master.group }}"
    mode: 0600
  when: master.generate_ssh_key

- name: install the ansible master scripts
  template:
    src: "{{ item }}.j2"
    dest: "{{ master.base_path }}/{{ item }}"
    owner: "{{ master.owner }}"
    group: "{{ master.group }}"
    mode: "0740"
  with_items:
    - provision.sh
    - run_ansible.sh
    - clone_ansible_repo.sh

- name: disable host key checking
  copy:
    src: ansible.cfg
    dest: "/home/{{ master.owner }}/.ansible.cfg"
    owner: "{{ master.owner }}"
    group: "{{ master.group }}"
    mode: 0644
  when: master.disable_host_key_checking

